openapi: 3.0.3
info:
  title: REPLACE
  version: REPLACE
paths:
  "/collection/":
    get:
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/collection"
components:
  schemas:
    collection:
      description: Generated Schema Goes Here
      type: object
